Produce separate disk images for Xen and QEMU
Amazon EC2 is based on Xen and so it wants Xen-style virtualized IO
devices, but QEMU wants virtio-style devices. This only really manifests
in our bootloader configuration, where we need to use the appropriate
device names for the console and root filesystem.

So we'll produce one root filesystem, but then produce separate boot
filesystems for each platform and then assemble them into two separate
full-disk images so that we can do local testing in QEMU while and yet
still upload results to EC2 for real-world testing and -- eventually --
actual deployment.

diff --git a/scripts/launch-emulator b/scripts/launch-emulator
--- a/scripts/launch-emulator
+++ b/scripts/launch-emulator
@@ -20,8 +20,8 @@ fi
 
 IMAGES_DIR="$(realpath $1)"
 
-if [ ! -f "$IMAGES_DIR/disk.img" ]; then
-   echo >&2 "Missing disk image file $IMAGES_DIR/disk.img.\n"
+if [ ! -f "$IMAGES_DIR/qemu-disk.img" ]; then
+   echo >&2 "Missing disk image file $IMAGES_DIR/qemu-disk.img.\n"
    echo >&2 "It's necessary to run buildroot and then run make-disk-image"
    echo >&2 "before we can boot the result in an emulator."
    exit 2
@@ -33,7 +33,7 @@ export PATH="$ROOT_DIR/toolchain/host/usr/sbin:$ROOT_DIR/toolchain/host/usr/bin:
 cd "$IMAGES_DIR"
 
 qemu-system-x86_64 \
-    -drive file="$IMAGES_DIR/disk.img",if=virtio,index=1,format=raw \
+    -drive file="$IMAGES_DIR/qemu-disk.img",if=virtio,index=1,format=raw \
     -chardev stdio,id=virtiocon0 \
     -device virtio-serial \
     -device virtconsole,chardev=virtiocon0 \
diff --git a/scripts/upload-ec2-image b/scripts/upload-ec2-image
--- a/scripts/upload-ec2-image
+++ b/scripts/upload-ec2-image
@@ -4,7 +4,7 @@
 # one of our buildroot image targets and subsequently augmented
 # by othe other script make-disk-image.
 #
-# It takes the created disk.img and loads it into AWS, first
+# It takes the created xen-disk.img and loads it into AWS, first
 # as an S3 bucket object, and then as an EBS snapshot, and
 # then finally as an AMI referring to that snapshot.
 #
@@ -26,15 +26,15 @@ IMAGES_DIR="$(realpath $1)"
 S3_URI="$2"
 AMI_NAME="$3"
 
-if [ ! -f "$IMAGES_DIR/disk.img" ]; then
-   echo >&2 "Missing disk image file $IMAGES_DIR/disk.img.\n"
+if [ ! -f "$IMAGES_DIR/xen-disk.img" ]; then
+   echo >&2 "Missing disk image file $IMAGES_DIR/xen-disk.img.\n"
    echo >&2 "It's necessary to run buildroot and then run make-disk-image"
    echo >&2 "before we can upload the result to EC2."
    exit 2
 fi
 
 echo "Uploading image to S3 at $S3_URI..."
-aws s3 cp "$IMAGES_DIR/disk.img" "$S3_URI"
+aws s3 cp "$IMAGES_DIR/xen-disk.img" "$S3_URI"
 
 echo "Importing image to EBS snapshot..."
 
